### PR TITLE
Exporting IntermediateValue Types

### PR DESCRIPTION
**Pull request by j1nma**
I've encountered an issue when trying to use IntermediateValue and its 'tags', these being (Population dna) (PointedDna dna) Int.
The following error message appeared at build:

```
Cannot find pattern `IntermediateValue`
134| updateSolution newFitness ( IntermediateValue p pd ng, seed )
```

With the change I did, it gets [fixed.](https://github.com/elm-lang/elm-lang.org/issues/523)

### CODE REVIEW

**Comment by ckoster22** [comment]
`IntermediateValue` is an [opaque type](https://medium.com/@ckoster22/advanced-types-in-elm-opaque-types-ec5ec3b84ed2) which means that its tag value is intentionally hidden and [other functions are exposed](https://github.com/ckoster22/elm-genetic/blob/2.0.0/src/Genetic.elm#L92-L101) so as to prevent breaking changes if one day I decide to change the value for `IntermediateValue`.

Please use `dnaFromValue`, `numGenerationsFromValue`, or `dnaFromValue` in combination with your own call to the function for `evaluateSolution` if you need to obtain the underlying values that `IntermediateValue` holds.

If you're trying to use it in some other way let me know and I can help out.

**Comment by j1nma** [comment]
I would need something like dnaToValue. I can't calculate my dna's fitness on its own, that's why I would need to update it externally. 

In my space invaders game, the invaders are best fitted if they last longer in the game (remain alive). That "last longer" is what is behind 'updateSolution newFitness'.

Thanks for your comment!

**Comment by ckoster22** [comment]
> In my space invaders game, the invaders are best fitted if they last longer in the game (remain alive). That "last longer" is what is behind 'updateSolution newFitness'.

That may be a little tricky. Let me know if you want ideas or get stuck!

**Comment by j1nma** [comment]
Yes, I would use any ideas you have in mind. Up to today I have this:

My population is made of space invaders. The fitness for the solution is based on how many in the game (not killed my a missile) share some trait of their Dna with the best Dna up to the moment (stored in IntermediateValue). For example, if the ideal Dna was [3,6,7] and the present invaders where [0,0,0] [3,4,2] [2,1,7], then the fitness for that Dna would be 2, because the middle one coincides with 3 and the last one with 7.

Can you imagine something smoother so as to not touch Genetic?

**Comment by ckoster22** [comment]
When looking at your code my first comment is you probably don't want [fitness in your DNA](https://github.com/j1nma/genetic-space-invaders/blob/master/src/GeneticHelper.elm#L19).

Secondly, [you shouldn't update IntermediateValue yourself](https://github.com/j1nma/genetic-space-invaders/blob/2d9a4d7d20de6bb9726b8b1c432ec157c6014d84/src/Update.elm#L131). The implementation that you provide for `evaluateSolution` will handle updating that solution's fitness score.

I haven't dug too deep but it seems like all you need to do is correct your `evaluateSolution` function to perform the fitness calculation instead of what it's doing now.

**Pull request closed without merging**
